### ISSUE TITLE
No longer connecting to onstar service

### ISSUE THREAD

**Issue by tdwhyt1216** [samrum/homebridge-onstar#209]
Plug-in is no longer connecting to onstar service. Possible bad secret key again?

**Comment by samrum** [comment]
Possibly! I published a new version.

**Comment by tdwhyt1216** [comment]
Still happening after update.
![2942A90E-1431-4F12-B28C-6AB3BB5159EE](https://user-images.githubusercontent.com/6132904/159714864-33d59fcf-8209-494c-ac0b-5c8c7f35b434.jpeg)

**Comment by samrum** [comment]
Are you both still able to trigger commands from myChevrolet app?

**Comment by tdwhyt1216** [comment]
Yes

**Comment by tdwhyt1216** [comment]
For what it’s worth, the myChevrolet app had 2 updates recently. Within 2
weeks of one another. No gui changes, so probably back end

**Comment by darklordbrock** [comment]
Yes, still able to remote start the car in the myChevrolet.

**Comment by tdwhyt1216** [comment]
Had the onstar plugin as a separate bridge once before, needed to remove the separate bridge from the home app and "un-separate" it. All works fine now.
